---

#Setting the variable for the list of invalid services. Invalid services are those services which are not installed
# on the server/machine
- set_fact:
    overall_services_status: []

- include_tasks: start.yml
  loop: "{{ services }}"
  loop_control:
    loop_var: service_name

- debug:
    var: overall_services_status