---

#all records is already populated when calling common role
- debug:
    var: all_records

- include_tasks: validate_user_records.yml
  args:
    apply:
      run_once: True
  loop: "{{ all_records }}"
  loop_control:
    loop_var: user_record

